/*
2p
1. 논리 설계
2. 데이터 모델링

3p
1. E-R모델
2. e-R모델
3. Entity

4p
1.E-R Diagram(Entity-Relation Diagram)
2. 관계

5p
1. 카디널리티
2. 옵셔널리티

6p
1.스키마
2.테이블

7p
1. table
2. index
3. sequence
*/

--1.
SELECT EMPNO AS EMPLOYEE_NO, ENAME AS EMPLOYEE_NAME, JOB, MGR AS MANAGER,HIREDATE,  SAL AS SALARY, COMM AS COMMISSION, DEPTNO AS DEPARTMENT_NO 
FROM EMP ORDER BY DEPTNO DESC, ENAME ASC ; 


--2-1.
SELECT * FROM EMP WHERE COMM IS NULL AND SAL IS NOT NULL;
  
-- 2-2.
 SELECT * FROM EMP 
 WHERE MGR IS NULL AND COMM IS NULL;
 
--3-1.
SELECT * FROM EMP WHERE ENAME LIKE '%S';

--3-2.
SELECT * FROM EMP WHERE JOB='SALESMAN' AND DEPTNO = 30 ;

--3-3.
SELECT * FROM EMP WHERE SAL > 2000 AND DEPTNO IN(20,30) ;

--3-4.
SELECT * FROM EMP WHERE SAL > 2000 AND DEPTNO = 20
UNION 
SELECT * FROM EMP WHERE SAL > 2000 AND DEPTNO = 30;


