SELECT ENAME FROM EMP WHERE DEPTNO = 20;
SELECT ENAME, JOB, SAL, DEPTNO FROM EMP WHERE DEPTNO = 20 AND JOB = 'ANALYST';

SELECT * FROM EMP WHERE SAL = 5000;
SELECT * FROM EMP WHERE SAL != 5000;
SELECT * FROM EMP WHERE SAL <> 5000;
SELECT * FROM EMP WHERE SAL ^= 5000;
SELECT * FROM EMP WHERE NOT SAL = 5000;
SELECT * FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP);

SELECT * FROM EMP WHERE ENAME LIKE 'M%';
SELECT * FROM EMP WHERE ENAME LIKE '_L%';
SELECT * FROM EMP WHERE ENAME LIKE '%AM%';
SELECT * FROM EMP WHERE ENAME NOT LIKE '%S';

SELECT * FROM EMP WHERE COMM = NULL;
SELECT * FROM EMP WHERE COMM IS NULL;
SELECT * FROM EMP WHERE MGR = NULL;
SELECT * FROM EMP WHERE MGR IS  NULL;


SELECT * FROM EMP WHERE SAL = 5000 AND SAL = 3000;
SELECT * FROM EMP WHERE SAL = 5000 OR SAL = 3000;
SELECT * FROM EMP WHERE SAL IN (3000,5000);
SELECT * FROM EMP WHERE JOB = 'ANALYST' OR JOB = 'KING' OR JOB = 'CLERK';
SELECT * FROM EMP WHERE JOB IN ('ANALYST','KING','CLERK');

SELECT EMPNO, ENAME, SAL, DEPTNO, JOB FROM EMP WHERE JOb = 'CLERK'
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO, JOB FROM EMP WHERE JOB = 'SALESMAN';

SELECT EMPNO, ename, sal, deptno FROM emp WHERE deptno = 10
UNION 
SELECT EMPNO, ENAME, SAL FROM EMP WHERE DEPTNO = 20;


SELECT EMPNO,ENAME,SAL,DEPTNO
      FROM EMP 
      INTERSECT
      SELECT EMPNO,ENAME,SAL,DEPTNO 
      FROM EMP
      WHERE DEPTNO = 10;
      
SELECT * FROM EMP WHERE UPPER(ENAME) = UPPER('scott');

SELECT ENAME, LENGTH(ENAME) AS LENGTH 
FROM EMP
WHERE LENGTH(ENAME) >= 5;

SELECT JOB, SUBSTR(JOB, -LENGTH(JOB)), SUBSTR(JOB, -LENGTH(JOB),2), SUBSTR(JOB, -3) FROM EMP;

SELECT * FROM EMP WHERE INSTR(ENAME, 'S')> 0;


SELECT '010-1234-5678' AS REPLACE_BEFORE
,REPLACE('010-1234-5678','-','') AS REPLACE_1
,REPLACE('010-1234-5678','-') AS REPLACE_2
FROM DUAL;

SELECT 'Oracle', LPAD('Oracle',10,'#') AS LPAD_1
,RPAD ('Oracle',10,'*') AS PRAD_1
,LPAD ('Oracle',10) AS LPAD_2
,RPAD('Oracle',10) AS RPAD_2
FROM DUAL;

SELECT EMPNO,ENAME, CONCAT(EMPNO,ENAME),
CONCAT(EMPNO,CONCAT(';',ENAME))
FROM EMP WHERE ENAME = 'SMITH';

SELECT '[' || TRIM('__Oracle__') || ']' AS TRIM,
'[' || TRIM(LEADING FROM '__Oracle__') || ']' AS TRIM_LEADING,
'[' || TRIM(TRAILING FROM '__Oracle__') || ']' AS TRIM_TRAILING,
'[' || TRIM(BOTH FROM '__Oracle__') || ']' AS TRIM_BOTH
FROM DUAL;


SELECT '[' || TRIM('_Oracle_') || AS TRIM,
'[' || LTRIM('_Oracle_') || AS LTRIM,


SELECT ROUND(1234.5678) AS R,
ROUND(1234.5678,0) AS R_0,
ROUND(1234.5678,1) AS R_1,
ROUND(1234.5678,2) AS R_2,
ROUND(1234.5678,-1) AS R_MINUS1,
ROUND(1234.5678,-2) AS R_MINUS2
FROM DUAL;

SELECT TRUNC(1234.5678) AS TRUNC,
TRUNC(1234.5678,0)

SELECT ABS(-100), ABS(100), ABS(0) FROM DUAL;

SELECT POWER(3,2), POWER(-3,3) FROM DUAL;

SELECT SIGN(-100), SIGN(100), SIGN(0) FROM DUAL;

SELECT SYSDATE AS NOW,
SYSDATE-1 AS YESTERDAY,
SYSDATE+1 AS TOMORROW
FROM DUAL;

SELECT SYSDATE, ADD_MONTHS(SYSDATE,3)
FROM DUAL;


-- 입사일로부터 20년 더한 일자
SELECT EMPNO, ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 12*20) AS WORK10YEAR
FROM EMP;

-- 입사일로부터 40년이상 근속
SELECT EMPNO, ENAME, HIREDATE, SYSDATE
FROM EMP
WHERE ADD_MONTHS(HIREDATE, 12*40) > SYSDATE;


SELECT SYSDATE,
NEXT_DAY(SYSDATE,'월요일'),
LAST_DAY(SYSDATE)
FROM DUAL;

SELECT ENAME,
EXTRACT(YEAR FROM HIREDATE) AS y,
EXTRACT(month FROM HIREDATE) AS m,
EXTRACT(day FROM HIREDATE) AS d
FROM EMP;

SELECT SYSDATE, ROUND(SYSDATE,'CC') AS FORMAT_CC,
ROUND(SYSDATE, 'YYYY') AS FORMAT_YYYY,
ROUND(SYSDATE,'Q') AS FORMAT_Q,
ROUND(SYSDATE, 'DDD') AS FORMAT_DDD,
ROUND(sYSDATE,'HH') AS FORMAT_HH
FROM DUAL;

SELECT EMPNO, ENAME, EMPNO + '500'
FROM EMP
WHERE ENAME = 'SCOTT';

SELECT 1300-'1500','1300' + 1500
FROM DUAL;


SELECT SYSDATE,
TO_CHAR(SYSDATE,'HH24:MI:SS') AS HH24MISS,
TO_CHAR(SYSDATE,'HH12:MI:SS AM') AS HH24MISS_AM,
TO_CHAR(SYSDATE,'HH12:MI:SS P.M.') AS HH24MISS_PM
FROM DUAL;

SELECT TO_NUMBER('3,300','999,999') - TO_NUMBER('1,100','999,999')
FROM DUAL;

SELECT TO_DATE('2023-02-15','YYYY-MM-DD') AS TODATE1,
TO_DATE('20150101','YYYY-MM-DD') AS TODATE2
FROM DUAL;

SELECT *
FROM EMP
WHERE HIREDATE>TO_DATE('1981/07/01','YYYY/MM/DD');


SELECT EMPNO, ENAME, SAL, COMM, SAL+COMM, NVL(COMM,0), SAL+NVL(COMM,0)
FROM EMP;

SELECT EMPNO,ENAME,COMM,
NVL2(COMM,'O','X'),
NVL2(COMM,SAL*12+COMM,SAL*12) AS ANNSAL
FROM EMP;


SELECT EMPNO, ENAME, JOB, SAL,
DECODE(JOB, 'MANAGER',SAL*0.2,
'SALESMAN',SAL*0.3,
'ANALYST',SAL*0.05,
SAL*0.1) AS BONUS
FROM EMP;

SELECT *
FROM EMP, DEPT
ORDER BY EMPNO;

SELECT *
FROM EMP E, DEPT D
WHERE ENAME = 'MILLER'
ORDER BY EMPNO;
